[package]
name = "apis"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.11", features = ["postgres"] }
dotenvy = "0.15.7"
poem = "3.1.11"
tokio = { version = "1.45.1", features = ["full"] }
db = {path = "../db"}
serde = { version = "1.0.219", features = ["derive"] }